### ISSUE TITLE
Cannot get this working

### ISSUE THREAD

**Issue by memolipd** [shurik/mezzanine_instagram#1]
due to the lack of a readme this module is useless. After installing via pip, adding the settings into the admin, none of the URL seem to work.

/ returns nothing.
/oauth errors as the page calling it is required to post a 'code' which is blank.
/delete returns nothing.
/ajax returns nothing.

Can you please provide a readme to get this working.

**Comment by shurik** [comment]
I've rebuilt this app as a conventional Python package, added documentation for installing and configuring it and tested it on a vanilla Mezzanine CMS install with an Instagram account. There's also documentation for a media stream feature.

The package is now on PyPi, so it's possible to install with `pip`.
